Add arch distro version detection.

diff --git a/bin/ruby-install b/bin/ruby-install
--- a/bin/ruby-install
+++ b/bin/ruby-install
@@ -25,10 +25,8 @@ if [[ ! $NO_INSTALL_DEPS -eq 1 ]]; then
 	install_deps || fail "Installing dependencies failed!"
 fi
 
-if [[ ! $BINARY_INSTALL -eq 1 ]]; then
-	setup_ruby || fail "Setup of $RUBY $RUBY_VERSION failed!"
-else
-	setup_binary || fail "Setup of $RUBY $RUBY_VERSION binary failed!"
+if [[ $BINARY_INSTALL -eq 1 ]]; then
+	setup_ruby_bin || fail "Setup of $RUBY $RUBY_VERSION binary failed!"
 fi
 
 if [[ ! $NO_DOWNLOAD -eq 1 ]]; then
